trigger:
  branches:
    include:
    - master
  paths:
    include:
      - AzureDevOpsBattleground/macros-invalid-properties1.yml

variables:
  - name: var_some_boolean
    value: true

steps:
  - pwsh: Write-Output 'some step'
    displayName: 'A task with macros in properties'
    enabled: $(var_some_boolean)
    continueOnError: $(var_some_boolean)
