trigger: none

pr: none

resources:
  repositories:
    - repository: dynamic-repository
      type: github
      endpoint: JakubLinhart
      name: JakubLinhart/AzureDevOpsBattlefield
      ref: $(var_defined_at_job_level)

jobs:
  - job: job1
    variables:
      - name: var_defined_at_job_level
        value: dynamicBranch
    steps:
      - checkout: dynamic-repository

      - pwsh: git status
