trigger: none

pr: none

resources:
  repositories:
    - repository: dynamic-repository
      type: github
      endpoint: JakubLinhart
      name: JakubLinhart/AzureDevOpsBattlefield
      ref: 701b91c2ba87176e44379d139ac5c4fcdbd818f5

steps:
  - checkout: dynamic-repository

  - pwsh: git status