trigger: none

pr: none

resources:
  repositories:
    - repository: dynamic-repository
      type: github
      endpoint: JakubLinhart
      name: JakubLinhart/AzureDevOpsBattlefield
      ref: $(var_defined_at_ui_level)

steps:
  - checkout: dynamic-repository

  - pwsh: git status
