trigger:
  branches:
    include:
    - master
  paths:
    include:
      - AzureDevOpsBattleground/macros-invalid-properties1.yml

tasks:
  - pwsh: Write-Output 'some step'
    displayName: 'A task with macros in properties'
    enabled: '$(var_some_boolean)' # doesn't pass pipeline start validation, because true/false is expected on compile time
    continueOnError: $(var_some_boolean) #  Unexpected value
