trigger:
  branches:
    include:
    - main
  paths:
    include:
      - pipelines/pipeline-parameters.yml

parameters:
  parameter1: value1

variables:
  - name: variableForParameter1
    value: ${{ parameters.parameter1 }}

steps:
  - checkout: none

  - pwsh: | 
      Write-Output 'template expression: ${{ parameters.parameter1 }}''
      Write-Output 'macro: $(parameter1)'
      Write-Output 'macro with variable value defined by pipeline parameter: $(variableForParameter1)'
    displayName: 'Parameter: ${{ parameters.parameter1 }}'