trigger:
  branches:
    include:
    - main
  paths:
    include:
      - pipelines/repository-resource-with-inline-syntax.yml

resources:
  repositories:
    - repository: repository
      type: github
      endpoint: JakubLinhart
      name: JakubLinhart/AzureDevOpsBattlefield

jobs:
  - job: job1
    displayName: Inline syntax combined with repository resource
    steps:
      - checkout: repository@refs/heads/dynamicBranch
