trigger:
  branches:
    include:
    - main
  paths:
    include:
      - pipelines/repository.yml

resources:
  repositories:
    - repository: repository
      type: github
      endpoint: JakubLinhart
      name: JakubLinhart/AzureDevOpsBattlefield

jobs:
  - job: job1
    displayName: Hardcoded checkout
    steps:
      - checkout: repository@dynamicBranch
