trigger:
  branches:
    include:
    - main
  paths:
    include:
      - pipelines/repository-macros.yml

variables:
  - name: var_defined_at_pipeline_level
    value: dynamicBranch

resources:
  repositories:
    - repository: dynamic-repository-ui-level
      type: github
      endpoint: JakubLinhart
      name: JakubLinhart/AzureDevOpsBattlefield
      ref: $(var_defined_at_ui_level)

    - repository: dynamic-repository-pipeline-level
      type: github
      endpoint: JakubLinhart
      name: JakubLinhart/AzureDevOpsBattlefield
      ref: $(var_defined_at_pipeline_level)

jobs:
  - job: job1
    displayName: UI level specified branch
    steps:
      - checkout: dynamic-repository-ui-level

      - pwsh: |
          echo 'A variable defined at UI level contains ''$(var_defined_at_ui_level)'' but is evaluated to a specific commit hash, so the result of a GIT checkout is a repository with a detached head.'
          git status

  - job: job2
    displayName: Pipeline level specified branch
    steps:
      - checkout: dynamic-repository-pipeline-level

      - pwsh: |
          echo 'A variable defined at pipeline level contains ''$(var_defined_at_pipeline_level)'' but is evaluated to a specific commit hash, so the result of a GIT checkout is a repository with a detached head.'
          git status
