trigger:
  branches:
    include:
    - main
  paths:
    include:
      - pipelines/repository.yml

resources:
  repositories:
    - repository: repository
      type: github
      endpoint: JakubLinhart
      name: JakubLinhart/AzureDevOpsBattlefield

jobs:
  - job: job1
    displayName: Hardcoded Github checkout
    steps:
      - checkout: git://JakubLinhart/AzureDevOpsBattlefield@dynamicBranch

  - job: job2
    displayName: Inline syntax combined with repository resource
    steps:
      - checkout: repository@dynamicBranch
