trigger: none
pr: none

variables:
  - name: var_some_boolean
    value: true

steps:
  - pwsh: Write-Output 'some step'
    enabled: '$[variables.var_some_boolean]'
    enabled: $[variables.var_some_boolean]
    continueOnError: $[variables.var_some_boolean]
