trigger: none
pr: none

variables:
  - name: var_some_string
    value: some string

steps:
  - checkout: none

  - pwsh: |
      Write-Output 'Environment variable cannot be defined by a runtime expression.'
      Write-Output 'If it would be possible then var_some_string environment variable wouldn''t be empty.'
      Write-Output "    env:var_some_string: '$env:var_some_string'"
    displayName: $[variables.var_some_string]
    env:
      var_some_string: $[variables.var_some_string]