trigger:
  branches:
    include:
    - main
  paths:
    include:
      - pipelines/secrets.yml

steps:
  - checkout: none

  - pwsh: |
      Write-Output "If any text contains a secret for example 'this is top secret' Azure DevOps server replaces it with '***'"
      Write-Output "The line above should contain 't h i s  i s  t o p  s e c r e t' (without inserted spaces)."
    displayName: Scrub secret value

  - pwsh: |
      Write-Output "ui-secret-variable shouldn't be in the following list:"
      Write-Output ""

      Get-ChildItem Env: | ForEach-Object {
        Write-Output "$($_.Name) = $($_.Value -split '' -join('-'))"
      }
    displayName: Print all environment variables

  - task: printAllVariables@1
    displayName: Print all variables

  - task: revealSecret@0.1.3
    displayName: Reveal secrets
    inputs:
      variableName: ui-secret-variable

  - pwsh: |
      Write-Output "Unmapped ui-secret-variable can be still used, for example via macro expansion."
      Write-Output "Revealed secret value from macro expansion:"
      Write-Output $(('$(ui-secret-variable)' -split '') -join('-'))
    displayName: Unmapped UI secret variable

  - pwsh: |
      Write-Output "Revealed secret value from a secret variable mapped to environment variable:"
      Write-Output $(($env:UI_SECRET_VARIABLE -split '') -join('-'))
    displayName: Mapped UI secret variable
    env:
      UI_SECRET_VARIABLE: $(ui-secret-variable)

  - pwsh: |
      Write-Output "The secret variable was mapped to environment variable in the previous step and it shouldn't be available for subsequent steps."
      Write-Output "Length of env:UI_SECRET_VARIABLE: $($env:UI_SECRET_VARIABLE.Length)"
      Write-Output "Value of env:UI_SECRET_VARIABLE: $(($env:UI_SECRET_VARIABLE -split '') -join('-'))"
    displayName: Check mapped UI secret from previous step
