trigger:
  branches:
    include:
    - main
  paths:
    include:
      - pipelines/secrets-UI-variables-must-be-mapped-to-environment-variables.yml

steps:
  - pwsh: |
      if ('$(ui-secret-variable') {
        Write-Output 'unmapped ui-secret-variable is not empty!'
        Write-Output 'revealed secret:'
        Write-Output $(('$(ui-secret-variable)' -split '') -join('-'))
        exit 1
      } else {
        Write-Output 'unmapped ui-secret-variable is empty ✓'
      }
    displayName: UI Secret variable without mapping

  - pwsh: |
      Get-ChildItem Env: | ForEach-Object {
        Write-Output "$($_.Name) = $($_.Value)"
      }