parameters:
  parameter1: 'parameter1 default value'
  parameter_final: 'parameter name define by other parameter'
  job_suffix: 'first'

jobs:
  - job: job2_${{ parameters.job_suffix }}
    dependsOn: job1
    steps:
      - pwsh: |
          Write-Output 'Parameter not defined in template but its value is specified as template argument.'
          Write-Output '    parameters.parameter_not_defined_in_template: ''${{ parameters.parameter_not_defined_in_template }}'''

          Write-Output ''
          Write-Output 'Undefined parameter is expanded to an empty string.'
          Write-Output '    parameters.parameter_without_default_value: ''${{ parameters.undefined_parameter }}'''
        displayName: 'Check weakly typed parameters'
