trigger:
  branches:
    include:
    - main
  paths:
    include:
      - pipelines/template-parameters-strong-invalid-default*.yml

variables:
  - name: some_variable
    value: true

steps:
  - template: template-parameters-strong-invalid-default-template-invalid.yml