parameters:
  parameter1: 'parameter1 default value'
  job_suffix: 'first'

jobs:
  - job: job2_${{ parameters.job_suffix }}
    dependsOn: job1
    steps:
      - checkout: none

      - pwsh: |
          Write-Output 'This is part of template-parameters-weak.yml'
          Write-Output '--------------------------------------------'
          Write-Output ''

          Write-Output 'Parameter not defined in the template, but its value is specified as a template argument.'
          Write-Output '    parameters.parameter_not_defined_in_template: ''${{ parameters.parameter_not_defined_in_template }}'''

          Write-Output ''
          Write-Output 'Undefined parameter is expanded to an empty string.'
          Write-Output '    parameters.undefined_parameter: ''${{ parameters.undefined_parameter }}'''
        displayName: 'Check weakly typed parameters'
