trigger: none

steps:
  - checkout: none

  - template: template-parameters-strong.yml
    parameters:
      parameter1: 'value of parameter1'
      parameter_without_default_value: 'an explicit value for a parameter without a default value'
      parameter_not_defined_in_template: 'value of parameter not defined in template'
